apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: intertodo-gapi
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intertodo-gapi
        tier: service
    spec:
      containers:
        - name: intertodo-gapi
          image: "intertodo-gapi:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000