kind: Service
apiVersion: v1
metadata:
  name: intertodo-gapi
  namespace: dev
spec:
  selector:
    app: intertodo-gapi
    tier: service
  ports:
  - protocol: TCP
    name: http
    port: 4000
    targetPort: 4000
  type: ClusterIP